/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StartInterviewRouteImport } from './routes/start-interview'
import { Route as InterviewIndexRouteImport } from './routes/interview/index'
import { Route as InterviewCompletedRouteImport } from './routes/interview/completed'
import { Route as InterviewFeedbackRouteImport } from './routes/interview/feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StartInterviewRoute = StartInterviewRouteImport.update({
  id: '/start-interview',
  path: '/start-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewCompletedRoute = InterviewCompletedRouteImport.update({
  id: '/interview/completed',
  path: '/interview/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewFeedbackRoute = InterviewFeedbackRouteImport.update({
  id: '/interview/feedback',
  path: '/interview/feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/start-interview': typeof StartInterviewRoute
  '/interview/completed': typeof InterviewCompletedRoute
  '/interview/feedback': typeof InterviewFeedbackRoute
  '/interview/': typeof InterviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/start-interview': typeof StartInterviewRoute
  '/interview/completed': typeof InterviewCompletedRoute
  '/interview/feedback': typeof InterviewFeedbackRoute
  '/interview': typeof InterviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/start-interview': typeof StartInterviewRoute
  '/interview/completed': typeof InterviewCompletedRoute
  '/interview/feedback': typeof InterviewFeedbackRoute
  '/interview/': typeof InterviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/start-interview'
    | '/interview/completed'
    | '/interview/feedback'
    | '/interview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/start-interview'
    | '/interview/completed'
    | '/interview/feedback'
    | '/interview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/start-interview'
    | '/interview/completed'
    | '/interview/feedback'
    | '/interview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  StartInterviewRoute: typeof StartInterviewRoute
  InterviewCompletedRoute: typeof InterviewCompletedRoute
  InterviewFeedbackRoute: typeof InterviewFeedbackRoute
  InterviewIndexRoute: typeof InterviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-interview': {
      id: '/start-interview'
      path: '/start-interview'
      fullPath: '/start-interview'
      preLoaderRoute: typeof StartInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/completed': {
      id: '/interview/completed'
      path: '/interview/completed'
      fullPath: '/interview/completed'
      preLoaderRoute: typeof InterviewCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/feedback': {
      id: '/interview/feedback'
      path: '/interview/feedback'
      fullPath: '/interview/feedback'
      preLoaderRoute: typeof InterviewFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  StartInterviewRoute: StartInterviewRoute,
  InterviewCompletedRoute: InterviewCompletedRoute,
  InterviewFeedbackRoute: InterviewFeedbackRoute,
  InterviewIndexRoute: InterviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
